### DISCUSSION TITLE
How to ingest data into the database in dependency order

### DISCUSSION THREAD

**Discussion by lgloege** [GHG-Tracker-Project/ghg-tracker-database#4] [Ideas]
We need a clean way to ingest data into the database so we do not run into errors on foreign key constraints. This is especially useful when populating the database for the first time. The order in which datasets are imported really matters. 

The problem we want to solve is we want a way to ingest data in dependency order and the ability to show the relationship. We are currently using a file that simply lists the datasets in a dependency order. The downside is the file is fragile, if the order changes then the data may not import properly. The file also does like show the dependencies between datasets. i.e. that dataset 2 depends on dataset 1 being imported first. 

Ideal solution would be define a DAG. This way we can map out the dependency of each dataset. For instance, country names need to be imported before state names into the Actor table. 

I am currently leaning towards using [pipelines with DVC](https://dvc.org/doc/user-guide/pipelines/running-pipelines). We are already using DVC to track the data in a remote data repository. This decreases the number of new tools we need to add to the stack and DVC allows pipelines to be defined with a simple YAML file. 

Other approaches include [apache airflow](https://airflow.apache.org/). But this has a slight learning curve and has lots of features that we don't even need, like job scheduling. Maybe a simpler approach is better. 

with `dvc repro`, we could define a yaml file like this:

```yaml
stages:
  import_dataset1:
    cmd: python importer.py dataset1
    outs: logs/dataset1

  import_dataset2:
    cmd: python importer.py dataset2
    deps: logs/dataset1
    outs: logs/dataset2
```

This shows that dataset1 is imported and that dataset2 depends on dataset1. dvc also has a `dvc dag` which displays the DAG of the workflow.

Are there better solutions than this?
